In [1]:
%autosave 20
import math 
import pandas as pd

Autosaving every 20 seconds

In [2]:
#Load the dataset
weather=pd.read_csv("weather.csv")
weather
weather.loc[weather['play']=='no','play']=0
weather.loc[weather['play']=='yes','play']=1
weather.head() 
P,N=weather['play'].value_counts()
print("yes :",P)
print("No :",N)

     outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

    outlook temperature humidity  windy  play
0     sunny         hot     high  False     0
1     sunny         hot     high   True     0
2  overcast         hot     high  False     1
3     rainy        mild     high  False     1
4     rainy        cool   normal  False     1

yes : 9
No : 5

In [3]:
# Function to calculate information gain
def informationGain(p,n):
    if(p==0):
        return 0
    elif(n==0):
        return 0    
    IG= -(p/(p+n))*math.log2(p/(p+n)) - (n/(p+n))*math.log2(n/(p+n))
    return round(IG,3)

In [4]:
IG=informationGain(P,N)
print("Total Information Gain : ",IG)

Total Information Gain :  0.94

In [5]:
j=0
Gain = pd.DataFrame(columns=['column', 'gain'])
for col in range(0,len(weather.columns)-1):
    b=weather.columns[col]
    print(b)
    cmn=[]

    cmn=weather.iloc[:,col].unique()
    ig=[]
    p1=[]
    n1=[]
    
    
    for col1 in range(0,len(cmn)):
        p=n=0
        print(cmn[col1])
        s=weather.groupby(b).get_group(cmn[col1])
#         print(s)
        p=len(s[s['play']==1])
        n=len(s[s['play']==0])    
        ig.append(informationGain(p,n))
        p1.append(p)
        n1.append(n)
#         print("information gain of ",cmn[col1], "is ",ig[col1])
             
    E=0.0
    for i in range(0,len(cmn)):
        E=E+(((p1[i]+n1[i])/(P+N))*ig[i])
        
    print("Entropy of ", b, "is ",round(E,3))
#     print("Gain of ",b, "is ",round(IG-E,3))
    Gain=Gain.append([{'column':b,'gain':round(IG-E,3)}], ignore_index=True)

#     print(Gain)
    print("***********")  
print(Gain.sort_values(by=['gain'],ascending=False))

outlook
sunny
overcast
rainy
Entropy of  outlook is  0.694
***********
temperature
hot
mild
cool
Entropy of  temperature is  0.911
***********
humidity
high
normal
Entropy of  humidity is  0.788
***********
windy
False
True
Entropy of  windy is  0.892
***********
        column   gain
0      outlook  0.246
2     humidity  0.151
3        windy  0.048
1  temperature  0.029

In [6]:
c=Gain.sort_values(by=['gain'],ascending=False).column.tolist()
c.append('play')
c

['outlook', 'humidity', 'windy', 'temperature', 'play']

In [7]:
weather=weather[c]
weather

     outlook humidity  windy temperature  play
0      sunny     high  False         hot     0
1      sunny     high   True         hot     0
2   overcast     high  False         hot     1
3      rainy     high  False        mild     1
4      rainy   normal  False        cool     1
5      rainy   normal   True        cool     0
6   overcast   normal   True        cool     1
7      sunny     high  False        mild     0
8      sunny   normal  False        cool     1
9      rainy   normal  False        mild     1
10     sunny   normal   True        mild     1
11  overcast     high   True        mild     1
12  overcast   normal  False         hot     1
13     rainy     high   True        mild     0

In [8]:
for col in range(0,len(weather.columns)-1):
    b=weather.columns[col]
    print(b)
    cmn=[]

    cmn=weather.iloc[:,col].unique()
    ig=[]
    p1=[]
    n1=[]
    
    print(cmn)
    for col1 in range(0,len(cmn)):
        p=n=0
        print(cmn[col1])
        s=weather.groupby(b).get_group(cmn[col1])
#         print(s)
        
        p=len(s[s['play']==1])
        n=len(s[s['play']==0])    
        print(p)
        print(n)
#         ig.append(informationGain(p,n))
#         p1.append(p)
#         n1.append(n)

outlook
['sunny' 'overcast' 'rainy']
sunny
2
3
overcast
4
0
rainy
3
2
humidity
['high' 'normal']
high
3
4
normal
6
1
windy
[False  True]
False
6
2
True
3
3
temperature
['hot' 'mild' 'cool']
hot
2
2
mild
4
2
cool
3
1