In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/HP/OneDrive - Newcastle University/Dissertation/Data_sets/training_data.csv")
df.head(5)

,Sensor,Type,Units,time,Flag,Value
0,PER_AIRMON_MESH301245,PM2.5,ugm -3,2020-05-21 03:45:00,0.0,5.640000
1,PER_AIRMON_MESH1911150,PM10,ugm -3,2020-05-30 18:44:00,0.0,6.357000
2,PER_AIRMON_MESH301245,PM10,ugm -3,2020-05-29 15:19:00,0.0,6.310000
3,PER_AIRMON_MESH1911150,PM 4,ugm -3,2020-05-24 14:56:00,0.0,0.380000
4,PER_EMOTE_1309,CO,ugm -3,2020-05-28 06:20:38,0.0,349.812463

In [2]:
def SensorMax(df):
    df_sensor=df.Sensor.unique()
    table=[]
    for j in range(0,len(df_sensor)):
        df1=df.loc[df.Sensor==df_sensor[j]]
        df_cols=df1.Type.unique()
        for i in range(0,len(df_cols)):
            df2=df1.loc[df1.Type==df_cols[i]]
    #         print("Minimum of {} is {}".format(df_cols[i],min(df1.Value)))
    #         print("Maximum of {} is {}".format(df_cols[i],max(df1.Value)))
            minmax=[df_sensor[j],df_cols[i],max(df2.Value),0]
            table.append(minmax)
    table=pd.DataFrame(table,columns=["sensor","type","max1","status"])
    table.to_csv("sensormax.csv",mode="w+",index=False)

In [3]:
# SensorMax(df)

In [4]:
def check(a,df2):
    if(a<=19.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==1):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-1
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==2):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-2
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==3):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-3
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==4):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-4
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
    if(a>=20.0 and a<25.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==0):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+1
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==2):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-1
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==3):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-2
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==4):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-3
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
    if(a>=25.0 and a<30.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==0):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+2
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==1):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+1    
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==3):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-1
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==4):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-2
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
    if(a>=30.0 and a<35.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==0):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+3
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==1):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+2
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==2):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+1
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==4):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()-1
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
    if(a>=35.0 and a<40.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==0):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+4
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==1):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+3
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==2):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+2
        elif(df2.loc[df2.type=="Temperature"].status.to_numpy()==3):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+1
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
    if(a>=40.0):
        if(df2.loc[df2.type=="Temperature"].status.to_numpy()==4):
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()
        else:
            df2.loc[df2.type=="Temperature","status"]=df2.loc[df2.type=="Temperature"].status.to_numpy()+4
        print("publish Danger")
    df2.loc[df2.type=="Temperature","max1"]=a
    df2.loc[df2.type=="Temperature"]
    df2.to_csv("sensormax.csv",mode="a",index=False,header=False)

In [6]:
df_max=pd.read_csv("sensormax.csv",names=["sensor","type","max1","status"])
df_max
df_sensor=df.Sensor.unique()

f = open("sensormax.csv", "w")
f.truncate()
f.close()
for j in range(0,len(df_sensor)):
    df1=df.loc[df.Sensor==df_sensor[j]]
    a=max(df1.loc[df1.Type=="Temperature"].Value)
    check(a,df_max.loc[df_max.sensor==df_sensor[j]])
df_max=pd.read_csv("sensormax.csv",names=["sensor","type","max1","status"])
df_max

                   sensor         type  max1  status
0   PER_AIRMON_MESH301245  Temperature  30.8       3
1  PER_AIRMON_MESH1911150  Temperature  25.4       2
2          PER_EMOTE_1309  Temperature  31.6       3

0

                   sensor         type  max1  status
0   PER_AIRMON_MESH301245  Temperature  30.8       3
1  PER_AIRMON_MESH1911150  Temperature  25.4       2
2          PER_EMOTE_1309  Temperature  31.6       3